# fly.toml app configuration file generated for turnitin on 2025-10-28T11:29:34+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turnitin'
primary_region = 'arn'

[build]

[env]
  MAX_CONCURRENCY = "3"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
